### ISSUE TITLE
mvp create portalname here error

### ISSUE THREAD

**Issue by Revenger** [Multiverse/Multiverse-Portals#103]
When I select points and make a portal using the command `/mvp create portalname here` I get this error in console.

22:42:54 [WARNING] [Multiverse-Core] Portal mining-main has an invalid DESTINATION!

In portals It created. 

```yaml
portals:
  main-mining:
    entryfee:
      currency: -1
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    owner: drguild
    location: -347.0,65.0,192.0:-347.0,85.0,200.0
    world: mining
```

I presumed by the document that here would mean my current location aka position e and world.

>Destination can either another portal (p:portalname), world (w:worldname), position (e:WORLD:X,Y,Z[:PITCH:YAW]), or current position (here).

Update I can use `/mvpm dest here` and that's fine
