### ISSUE TITLE
Portals cannot be loaded, format error

### ISSUE THREAD

**Issue by Gragog** [Multiverse/Multiverse-Portals#522]
Issue: When the server starts, the MV-Portals cannot be loaded.
The console says: `[MVPLogging] Failed Parsing Location for: world (Format Error, was expecting: 'X,Y,Z:X,Y,Z', but got: '')`

The saved `portals.yml`:
```yaml
portals:
  world:
    main:
      entryfee:
        amount: 0.0
      safeteleport: true
      teleportnonplayers: false
      handlerscript: ''
      owner: GRAMINI
      location: -151.0,65.0,-175.0:-151.0,67.0,-171.0
      world: world
      destination: e:main:217.0,64.0,-204.0:0.0:0.0
    entryfee:
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    handlerscript: ''
    owner: ''
```
The `location` looks right, `X,Y,Z:X,Y,Z`

Server is running `openjdk 12.0.2 2019-07-16` on Ubuntu 19.04
